/**
 * seedDefaults.ts
 * Seeds Supabase tables with all existing site content only if tables are empty.
 * Safe to call on every app load — never overwrites existing data.
 */
import { supabase } from './supabase';

// ─── FAQs ────────────────────────────────────────────────────────────────────
const DEFAULT_FAQS = [
  { question: "How do you work?", answer: "I start by understanding your business and what the site needs to achieve. Then I define the structure, design the layout, build it in clean code, test it, and hand it over live. You're updated at every stage — no surprises.", order_index: 0 },
  { question: "How long does a project take?", answer: "A standard business website takes 1–2 weeks. Landing pages can be done in 3–5 days. Larger web applications are scoped per project. I give you a clear timeline before we start.", order_index: 1 },
  { question: "How much do you charge?", answer: "Pricing depends on the scope of the project. A basic business website starts from $300. Landing pages start from $150. I offer flat-fee pricing — no hidden costs, no hourly surprises. Message me and I'll give you an exact quote.", order_index: 2 },
  { question: "How many revisions do I get?", answer: "You get 2 rounds of revisions included in every project. I build to your brief from the start, so most clients don't need more than one round. Additional revisions beyond that are available at a small flat fee.", order_index: 3 },
  { question: "Do you offer support after launch?", answer: "Yes. Every project includes 2 weeks of free post-launch support. After that, I offer affordable monthly maintenance packages covering updates, performance monitoring, and content changes.", order_index: 4 },
  { question: "What's your pricing model?", answer: "I charge a flat project fee — not hourly. You know the full cost before I write a single line of code. 50% upfront, 50% on delivery. No retainers unless you want ongoing maintenance.", order_index: 5 },
];

// ─── Site Content ─────────────────────────────────────────────────────────────
const DEFAULT_SITE_CONTENT = [
  { section: 'hero', key: 'headline', value: 'I Build Websites That Generate Leads, Sales, and Growth' },
  { section: 'hero', key: 'subheadline', value: 'Full-Stack Web Developer helping businesses and founders build fast, conversion-focused websites — written in real code, no templates, no shortcuts.' },
  { section: 'hero', key: 'availability', value: '✦ A BlueStark Initiative' },
  { section: 'about', key: 'title', value: 'The Developer Behind the Work.' },
  { section: 'about', key: 'bio', value: "Hi, I'm Isaac Testimony — a Full-Stack Web Developer and final-year Civil Engineering student. My engineering background shapes everything I build. I think in systems, plan before I write a single line of code, and solve problems from first principles.\n\nWhen I build your website, I'm thinking about structure, performance, and how it holds up under real-world pressure — the same discipline I apply to engineering problems.\n\nI personally handle everything: the architecture, the frontend, the backend, and the launch. No handoffs, no communication gaps, no agency markup." },
  { section: 'stats', key: 'stat1_val', value: '15+' },
  { section: 'stats', key: 'stat1_lbl', value: 'Projects Delivered' },
  { section: 'stats', key: 'stat2_val', value: '10+' },
  { section: 'stats', key: 'stat2_lbl', value: 'Happy Clients' },
  { section: 'stats', key: 'stat3_val', value: '2+' },
  { section: 'stats', key: 'stat3_lbl', value: 'Years Building' },
  { section: 'stats', key: 'stat4_val', value: '100%' },
  { section: 'stats', key: 'stat4_lbl', value: 'On-Time Delivery' },
  { section: 'services', key: 'title', value: 'Engineered Solutions.' },
  { section: 'services', key: 'desc', value: "I don't just build websites; I audit failing platforms and engineer the exact solution required to scale." },
  { section: 'pain_points', key: 'title', value: "You've Got the Vision. The Build Is Where It Falls Apart." },
  { section: 'pain_points', key: 'desc', value: "These aren't hypothetical struggles. These are the exact conversations I have every week with founders who found me right before they gave up." },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
const DEFAULT_TESTIMONIALS = [
  { name: "Austin Dental Clinic", position: "Owner", company: "Austin Elite Smiles", body: "Isaac completely transformed our website. The new smart triage system dramatically increased our high-ticket veneer bookings within the first week of launch. Genuinely impressive work.", avatar_url: "", order_index: 0 },
  { name: "Impact Pest Team", position: "Operations Lead", company: "Impact Pest Control", body: "We went from almost no web leads to a steady stream of calls after Isaac rebuilt our site. It's fast, it looks professional, and it actually converts. Best investment we made.", avatar_url: "", order_index: 1 },
  { name: "WeGlobalee Team", position: "CTO", company: "WeGlobalee", body: "The portal Isaac engineered handles our entire global logistics data cleanly. Complex multi-role access, massive datasets — all rendering flawlessly. He knew exactly what we needed.", avatar_url: "", order_index: 2 },
];

// ─── Blog Posts ───────────────────────────────────────────────────────────────
const DEFAULT_BLOG_POSTS = [
  {
    title: 'How I Audit a Dental Website for SEO and Conversions',
    slug: 'how-i-audit-a-dental-website',
    excerpt: 'A deep dive into my process for tearing down poorly performing luxury dental sites and engineering them for high-ticket leads.',
    category: 'Website Auditing',
    readTime: '6 min read',
    date: 'March 4, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1600&auto=format&fit=crop',
    content: `# The Blueprint for High-Ticket Medical Funnels\n\nWhen a client comes to me with a failing luxury dental website, the issue is almost never the traffic. It's the architecture.\n\nThey are driving $10k/month in ads to a site that treats a $30,000 veneer patient exactly the same as someone looking for an $80 cleaning. This guarantees friction, frustration, and bounce rates.\n\n## 1. The UX Teardown\nFirst, I map the user flow. Where is the "Book Now" button leading? Usually, it's a generic contact form with 15 required fields.\n\n**The Fix:** I build a "Smart Triage" system. A React-based modal that asks 3 simple questions: "What is your main concern?", "What is your timeline?", "What is your budget?". Based on the answers, high-ticket leads are routed directly to a VIP concierge calendar.\n\n## 2. The Performance Audit\nLuxury means speed. If a page takes 4 seconds to load its massive stock images, the luxury illusion shatters.\n\n**The Fix:** I rebuild the foundation. I lazy-load every image outside the viewport, compress hero visuals to next-gen formats (WebP/AVIF), and strip out bloated WordPress plugins in favor of a lean React/Next.js architecture.\n\n## 3. The Visual Hierarchy\nA premium service needs a premium aesthetic. Dark mode accents, subtle Framer Motion reveals, and crisp typography.\n\n## Conclusion\nA website is not a brochure; it is an engineered sales machine.`,
    published: true,
  },
  {
    title: 'Traditional Coding vs. No-Code & WordPress: The Hard Truth',
    slug: 'traditional-coding-vs-no-code',
    excerpt: 'The reality of when to use No-Code tools, and when you absolutely need custom web development.',
    category: 'Architecture',
    readTime: '5 min read',
    date: 'February 28, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1600&auto=format&fit=crop',
    content: `# Breaking the No-Code Illusion\n\nNo-code tools like Webflow and Framer are incredible for rapid prototyping and simple marketing sites. However, selling them as the ultimate solution for complex SaaS platforms or highly secure enterprise tools is a dangerous game.\n\n## When Custom Engineering Wins\n\n1. **Complex Logic:** If your application requires intricate state management, complex data relationships, or custom algorithms, dragging and dropping won't cut it.\n2. **Performance at Scale:** WordPress and heavy page builders inherently output bloated DOM structures. Custom React/Vite builds achieve perfect core web vitals because you control every single byte of code shipped to the browser.\n3. **Security & Control:** When you rely on third-party plugins to hold your platform together, every update is a terrifying game of Russian Roulette. Custom code means you own the architecture.\n\nI use the right tool for the job. But when it matters, I write code.`,
    published: true,
  },
  {
    title: 'The Future of Web Development: AI Integrated Interfaces',
    slug: 'future-of-web-development',
    excerpt: 'How AI is changing the way users interact with the web, and how developers need to adapt.',
    category: 'AI & Engineering',
    readTime: '8 min read',
    date: 'February 15, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1600&auto=format&fit=crop',
    content: `# Beyond the Static Page\n\nThe era of navigating through deeply nested menus is ending. The future interface is generative, predictive, and wildly conversational.\n\n## The Shift in UI/UX\nThe web is moving from "Click here to find this" to "Ask for this, and the UI builds itself to show it." This requires a completely different architectural approach.\n\nInstead of hardcoding every possible UI state, engineers must now build dynamic component systems that an AI layer can compose on the fly.\n\n## What This Means for Engineers\nIf you only know how to center a div and fetch a REST API, you are falling behind. Developers must learn:\n- **Vector Databases & RAG:** Integrating semantic search deeply into the frontend.\n- **Streaming Architectures:** Handling real-time, token-by-token responses smoothly without judder.\n- **Agentic Workflows:** Building interfaces that act on behalf of the user, not just display data.\n\nThe web is getting smarter. My code needs to keep up.`,
    published: true,
  },
  {
    title: 'How Websites Fail: Functionality Over Form',
    slug: 'how-websites-fail-functionality',
    excerpt: 'Why beautiful websites consistently lose money, and how engineering functional conversion architecture is the only design that matters.',
    category: 'Conversion Architecture',
    readTime: '7 min read',
    date: 'March 6, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1600&auto=format&fit=crop',
    content: `# The Aesthetic Trap\n\nI see it every single week. A founder drops $15,000 on an award-winning creative agency. The website is delivered. It has 3D WebGL renders, cinematic scroll tracking, custom cursors, and 4K autoplaying background videos.\n\nIt wins a CSS design award.\n\nAnd then... crickets. The bounce rate is 85%. The conversion rate is 0.2%.\n\n## Design is Not Functionality\nBeautiful design builds trust, but **functionality drives revenue**. When a user visits your site, they are trying to solve a specific problem. If your 3D animations block them from understanding how to give you their money in the first 5 seconds, you have failed.\n\n### The 3 Core Pillars of a Functional Website:\n\n1. **Ultra-Fast Value Proposition:** A razor-sharp H1 dominating the viewport.\n2. **Frictionless Architecture:** Put the CTA everywhere. Make the paths to revenue direct.\n3. **Performance as a Feature:** You cannot have a functional website if it takes 4 seconds to become interactive on mobile.\n\n## The Engineering Solution\nI don't start with colors and fonts. I start with the database architecture, the routing strategy, and the conversion funnel. Only once the engine is flawlessly constructed do I paint the car.`,
    published: true,
  },
];

// ─── Projects ─────────────────────────────────────────────────────────────────
const DEFAULT_PROJECTS = [
  { slug: 'austin-elite-smiles', title: 'Austin Elite Smiles', category: 'Luxury Dental UX', description: 'A complete Website Audit & Redesign for a luxury dental clinic. By identifying UX friction—specifically treating high-ticket veneer leads like standard cleaning leads—I engineered a custom "Smart Triage" React modal and an immersive "Atmosphere Video" hero to significantly increase VIP conversions.', techStack: ['React', 'Site Audit', 'CRO', 'Tailwind CSS'], liveUrl: 'https://austin-smiles.vercel.app/', imageUrl: '', type: 'client', order_index: 0, caseStudy: { overview: 'Austin Elite Smiles handles high-ticket VIP patients. A thorough website audit revealed critical UX friction: the original site treated a $30,000 veneer lead identical to an $80 cleaning lead.', challenges: ['Generic funnel creating high friction for premium clients.', 'High bounce rates due to an uninspiring visual atmosphere.', 'No clear segregation between routine care and luxury cosmetic procedures.'], solutions: ['Engineered a custom "Smart Triage" React modal that segments visitors based on their exact needs.', 'Implemented an "Atmosphere Video" hero to immediately establish trust and luxury branding.', 'Streamlined the conversion process specifically for high-ticket veneer leads.'], results: ['Dramatically increased VIP conversion rates.', 'Reduced bounce rate through instant visual engagement.', 'Clean, actionable lead generation data provided to the clinic.'] } },
  { slug: 'impact-pest', title: 'Impact Pest', category: 'Lead-Gen Website', description: 'A completely functional, high-converting lead generation platform built for a pest control company. This project directly connects localized SEO with an ultra-fast frontend to capture residential and commercial leads before they bounce to competitors.', techStack: ['React', 'SEO Optimization', 'Lead Gen', 'Tailwind'], liveUrl: 'https://impactpest-com.vercel.app/', imageUrl: '', type: 'client', order_index: 1, caseStudy: { overview: 'Impact Pest needed a dominant local presence to outrank established competitors. Their previous site was a slow, templated brochure that leaked potential leads.', challenges: ['Outdated templated design failing to convert mobile traffic.', 'Extremely slow load times harming Google Business Profile rankings.', 'Lack of clear trust signals and immediate call-to-actions for stressed homeowners.'], solutions: ['Engineered a blazingly fast React frontend ensuring sub-second load times on 3G networks.', 'Structured the UI entirely around immediate lead capture.', 'Implemented rigorous on-page technical SEO to dominate local search queries.'], results: ['Massive spike in highly localized, qualified leads.', 'Zero-friction mobile experience leading to higher call volumes.', 'A scalable platform ready to expand into new service territories.'] } },
  { slug: 'curtsy', title: 'Curtsy App', category: 'P2P Marketplace', description: 'A modern, ultra-clean P2P fashion marketplace. Engineered massive feeds of high-quality clothing items, intricate user profile interactions, and heavily complex filtering and search mechanisms optimized for mobile conversion.', techStack: ['React', 'GraphQL', 'Algolia', 'Tailwind'], liveUrl: 'https://curtsyapp.com', imageUrl: '', type: 'client', order_index: 2, caseStudy: { overview: 'Curtsy is a rapidly growing P2P marketplace. The core engineering requirement was speed — instantaneous, infinite-scrolling results mapped precisely against dense inventory databases.', challenges: ['Infinite scrolling feeds lagging heavily on mid-range Android and older iOS devices.', 'Complex multi-variable filtering slowing down DB queries.', 'Messy, untrusted user-uploaded images ruining aesthetic consistency.'], solutions: ['Re-architected the main product feed using virtualization techniques to ensure 60fps scrolling.', 'Integrated Algolia Search pipelines natively for sub-10ms query returns.', 'Built a client-side image cropping and normalization pipeline.'], results: ['Liquid-smooth infinite scrolling unlocked massive increases in session duration.', 'Lightning-fast filter manipulation drove higher cart-add rates.', 'A highly scalable, universally aesthetic marketplace.'] } },
  { slug: 'blessed-olas', title: 'Blessed Olas', category: 'Modern Web App', description: 'A modern, conversion-optimized web application engineered for scalability. This project focused heavily on clean architectural principles, perfect mobile responsiveness, and an incredibly smooth user experience.', techStack: ['React', 'Clean Arch', 'Responsive', 'UX Design'], liveUrl: 'https://blessed-olas.vercel.app/', imageUrl: '', type: 'client', order_index: 3, caseStudy: { overview: 'Blessed Olas needed a completely modern web application that not only looked great but was architected for optimal conversions and smooth user traversal.', challenges: ['Lack of structural clarity leading to confused user journeys.', 'Poor mobile optimization causing traffic drop-offs.', 'A need for pure, scalable code architecture.'], solutions: ['Prioritized clean architecture and maintainable code for extreme scalability.', 'Engineered perfect mobile responsiveness, ensuring the application feels native on any device.', 'Optimized the entire UX flow to guide visitors intuitively to the primary call-to-action.'], results: ['Massively improved mobile conversion pipeline.', 'A consistently smooth user experience free of structural friction.', 'A resilient, maintainable codebase ready for future feature expansion.'] } },
  { slug: 'rise-fairsketch', title: 'Rise Fairsketch', category: 'SaaS', description: 'An enterprise-scale productivity suite dashboard designed to drastically reduce cognitive load.', techStack: ['React', 'TypeScript', 'Redux'], liveUrl: 'https://rise.fairsketch.com', imageUrl: '', type: 'client', order_index: 4, caseStudy: { overview: 'Fairsketch needed a rigid, highly typed dashboard capable of digesting massive real-time project metrics.', challenges: ['Deeply nested state objects causing infinite re-renders.', 'Complex drag-and-drop mechanics rendering slowly.'], solutions: ['Architected a flattened Redux state lattice.', 'Integrated strictly memoized drag-and-drop contexts.'], results: ['Utterly solid 60fps interaction models.', 'Massive reduction in memory profiling spikes.'] } },
  { slug: 'weglobalee', title: 'WeGlobalee', category: 'Portal', description: 'A complex, multi-tenant portal application orchestrating extensive global logistics flows.', techStack: ['React', 'Dashboards', 'API Auth'], liveUrl: 'https://app.weglobalee.com', imageUrl: '', type: 'client', order_index: 5, caseStudy: { overview: 'WeGlobalee acts as the central hub for global supply chains, requiring strict data access controls and complex tabular rendering.', challenges: ['Rendering immense datasets without locking the browser.', 'Complex multi-role authorization layers.'], solutions: ['Implemented strict windowed list virtualization.', 'Engineered middleware-level JWT parsing.'], results: ['Liquid-smooth scrolling on huge datasets.', 'Absolute security compliance.'] } },
  { slug: 'eaasyreels', title: 'Eaasyreels', category: 'Creator Platform', description: 'A high-performance, visually engaging portfolio built specifically for a videographer and content creator. Engineered with a sleek dark-mode aesthetic, the platform focuses on ultra-fast load times and fluid media playback.', techStack: ['Next.js', 'Media Stream', 'Performance', 'Dark Mode'], liveUrl: 'https://eaasyreels.vercel.app/', imageUrl: '', type: 'client', order_index: 6, caseStudy: { overview: "Eaasyreels required a platform that matched the visual fidelity of their video content. A videographer's portfolio lives and dies by media performance.", challenges: ['Balancing high-quality massive video assets with rapid page load speeds.', 'Creating an interface that doesn\'t distract from the actual content.', 'Ensuring perfectly smooth scrolling and media playback across all devices.'], solutions: ['Built a custom dark-mode aesthetic that allows the vibrant video content to pop.', 'Engineered a highly optimized media pipeline ensuring ultra-fast load times.', 'Implemented fluid video playback components.'], results: ['Sub-second load times despite heavy, uncompromised media files.', 'A sleek, cinematic user experience.', 'Higher engagement times as visitors explore the video galleries.'] } },
  { slug: 'hatch-collection', title: 'Hatch Collection', category: 'Luxury Maternity D2C', description: 'Designed and deployed a chic, high-end editorial commerce platform. Blended high-fashion editorial content directly with a highly optimized, high-converting Shopify cart pipeline.', techStack: ['Next.js', 'Shopify', 'Framer Motion', 'React'], liveUrl: 'https://www.hatchcollection.com', imageUrl: '', type: 'client', order_index: 7, caseStudy: { overview: 'Hatch Collection bridges the gap between high-fashion editorial and D2C commerce.', challenges: ['Rigid, heavily customized CSS grid layouts breaking across non-standard viewport sizes.', 'Integrating a complex, high-res editorial CMS (Sanity) directly with a transaction engine (Shopify).', 'Creating liquid-smooth page transitions to emulate physical magazine turning.'], solutions: ['Engineered a fluid, deeply responsive CSS Grid foundation.', 'Built a custom Next.js middleware bridge to instantly sync Sanity editorial content with live Shopify inventory.', 'Implemented strict Framer Motion orchestration for smooth, hardware-accelerated page transitions.'], results: ['A flawlessly premium, uncompromised luxury shopping experience.', 'Eliminated inventory mismatches between editorial features and live stock.', 'Significant increase in Average Order Value (AOV).'] } },
  { slug: 'kittenish', title: 'Kittenish', category: 'Fast-Fashion D2C', description: 'A vibrant, high-energy fashion boutique platform engineered for massive traffic spikes. Built a deeply optimized, highly dynamic product grid capable of handling extreme fast-fashion inventory turnover.', techStack: ['React', 'GraphQL', 'Redis', 'Vercel'], liveUrl: 'https://kittenish.com', imageUrl: '', type: 'client', order_index: 8, caseStudy: { overview: 'Kittenish operates in the hyper-fast world of trendy fast-fashion. The platform required an architecture capable of surviving massive concurrent loads.', challenges: ['Database bottlenecking during major influencer-driven collection drops.', 'Rendering hundreds of unique, dynamically requested product cards smoothly.', 'Maintaining a strict pink/gold visual aesthetic across aggressively changing inventory datasets.'], solutions: ['Bypassed the primary database utilizing a highly distributed Redis edge caching layer.', 'Implemented strict DOM virtualization mapping for the main infinite-scrolling product grid.', 'Built a centralized Tailwind design-token system.'], results: ['The platform successfully absorbed 10x traffic multipliers during collection drops.', 'Flawless, jitter-free infinite scrolling across massive product catalogs.', 'A highly vibrant, instantly recognizable brand storefront UI.'] } },
  { slug: 'opositiv', title: 'O Positiv', category: 'Clinical Wellness SaaS', description: 'Architected a highly interactive, clinical-grade D2C subscription platform for health supplements. Engineered a bespoke subscription builder paired with deep data visualizations regarding active ingredient efficacy.', techStack: ['Next.js', 'Stripe', 'D3.js', 'TypeScript'], liveUrl: 'https://opositiv.com', imageUrl: '', type: 'client', order_index: 9, caseStudy: { overview: 'O Positiv combines D2C wellness with clinical data. The user interface needed to project extreme medical trust while guiding users through a complex, personalized supplement subscription builder.', challenges: ['High drop-off rates in the multi-step personalized subscription onboarding funnel.', 'Displaying complex clinical ingredient data without overwhelming the user.', 'Navigating intricate recurring billing edge cases cleanly in the UI.'], solutions: ['Engineered a highly fluid, optimistic-UI driven onboarding wizard.', 'Integrated custom, interactive D3.js ingredient visualizations.', 'Built a centralized, rigorously tested TypeScript state machine to hand off flawless billing mutations to Stripe.'], results: ['Drastic improvements in personalized subscription completion rates.', 'Established immense consumer trust via clinical, interaction-driven ingredient data mapping.', 'A profoundly stable, beautifully clinical white-and-peach dashboard architecture.'] } },
  { slug: 'nupt-ai', title: 'Nupt AI', category: 'Computer Vision SaaS', description: 'A high-end photography editing platform powered by Machine Learning. I architected the real-time processing pipeline and the responsive React interface allowing photographers to bulk-process thousands of raw images instantly.', techStack: ['Next.js', 'Python API', 'Data Viz', 'Vercel'], liveUrl: 'https://nupt.ai/', imageUrl: '', type: 'client', order_index: 10, caseStudy: { overview: 'Nupt handles massive payloads of RAW photography. The frontend needed to effortlessly accept gigabytes of data and stream progress to the user via WebSockets.', challenges: ['Managing massive multi-file client-side uploads without crashing the browser tab.', 'Communicating real-time AI processing progress back to the user smoothly.', 'Rendering hundreds of high-res edited outputs instantly.'], solutions: ['Built a multi-threaded chunking upload client bypassing standard browser file-size limits.', 'Implemented full WebSocket integration to deliver granular, per-image progress bars.', 'Designed a high-end, bright-mode minimalist UI.'], results: ['Photographers can now process entire wedding albums without single browser failure.', 'Extremely high user retention driven by an incredibly satisfying, frictionless UI.', 'A scalable frontend specifically engineered to handle limitless asset arrays.'] } },
  { slug: 'scentbird', title: 'Scentbird', category: 'Enterprise D2C', description: 'Scaled the digital storefront architecture for a leading D2C fragrance subscription platform. Focused strictly on Conversion Rate Optimization (CRO), reducing subscription checkout friction, and drastically improving the mobile discovery experience.', techStack: ['React', 'Stripe', 'GraphQL', 'Tailwind'], liveUrl: 'https://www.scentbird.com', imageUrl: '', type: 'client', order_index: 11, caseStudy: { overview: 'Scentbird moves immense volume. At this enterprise scale, a 1% drop in conversion equals millions in lost revenue.', challenges: ['High mobile cart-abandonment rate due to a bloated legacy checkout system.', 'Extremely slow product discovery pages caused by hundreds of high-res image requests.', 'Complex recurring billing logic confusing first-time users.'], solutions: ['Redesigned the entire onboarding quiz flow and checkout pipeline using strict single-page (SPA) state.', 'Migrated legacy REST APIs to a highly cached GraphQL edge network.', 'Implemented rigorous A/B testing frameworks across the primary funnel.'], results: ['Achieved a double-digit increase in completed subscription checkouts.', 'Slashed mobile interaction latency globally.', 'Delivered a frictionless, luxury user experience mapped to strict ADA compliance.'] } },
  { slug: 'betterlegal', title: 'BetterLegal', category: 'Legal Tech SaaS', description: 'An enterprise-grade, high-trust Legal SaaS application dashboard. Built for strict security, displaying corporate document generation, progress trackers for LLC formation, and intricately validated secure data-entry forms.', techStack: ['React', 'Security', 'FinTech', 'Next.js'], liveUrl: 'https://app2.betterlegal.com', imageUrl: '', type: 'client', order_index: 12, caseStudy: { overview: 'BetterLegal requires maximum user trust. Handling sensitive corporate documents, EIN formations, and routing financial data means the UI must feel impenetrable.', challenges: ['Form abandonment rates caused by overwhelming, overly complex legal questionnaires.', 'Ensuring strict frontend data sanitization before transmitting sensitive PII.', 'Creating a dark-blue, enterprise-tier aesthetic that projects institutional authority.'], solutions: ['Engineered a highly intelligent, multi-step React form wizard that contextualizes questions and auto-saves progress constantly.', 'Implemented rigorous Zod schema validation across all inputs.', 'Designed a stark navy-blue and white dashboard focusing purely on typography and whitespace.'], results: ['Drastic reduction in LLC formation abandonment rates.', 'Zero security incidents originating from client-side vulnerability.', 'A highly authoritative, enterprise-grade architecture actively trusted by thousands of businesses.'] } },
  { slug: 'carma-earth', title: 'Carma', category: 'Climate Data Dashboard', description: 'A climate-tech sustainability data dashboard engineered to visualize complex metrics. Displaying interactive maps plotting global offset projects, intricate metrics tracking widgets, and stark, transparent reporting logics.', techStack: ['React', 'Mapbox', 'D3.js', 'Vercel'], liveUrl: 'https://carma.earth', imageUrl: '', type: 'client', order_index: 13, caseStudy: { overview: 'Carma aims to transparently map global carbon offsets. The frontend challenge was rendering immense volumes of geospatial and statistical data in a way that was instantly digestible.', challenges: ['Rendering heavy interactive maps overloaded with data points crashing browsers.', 'Translating complex climate science data into clean, readable dashboard widgets.', 'Creating a green/slate aesthetic uniquely modern.'], solutions: ['Integrated Mapbox GL natively, clustering geospatial data efficiently to ensure smooth 60fps panning.', 'Engineered custom D3.js charting components for deep, high-performance data visualizations.', 'Executed an emerald-green and dark-slate UI system.'], results: ['A profoundly functional, deeply beautiful sustainability dashboard.', 'Fluid, interactive data exploration previously impossible on older architectures.', 'Established absolute domain authority through a pure, uncompromised front-end experience.'] } },
  { slug: 'oceanair-travels', title: 'OceanAir Travels', category: 'Landing Page', description: 'A heavily optimized travel and tourism platform handling immense visual media without stuttering.', techStack: ['React', 'Next.js', 'Image Caching'], liveUrl: 'https://www.oceanairtravels.com', imageUrl: '', type: 'client', order_index: 14, caseStudy: { overview: 'Travel sites are notoriously heavy. OceanAir required an architecture that loaded ultra-HD video backgrounds effortlessly.', challenges: ['Heavy LCP penalties from background videos.', 'Cluttered mobile nav systems.'], solutions: ['Engineered aggressive lazy-loading Intersection Observers.', 'Built an elegant, hardware-accelerated mobile side-sheet.'], results: ['Sub-second First Input Delay.', 'Massive spike in mobile bookings.'] } },
  { slug: 'california-realty', title: 'California Realty', category: 'Landing Page', description: 'A localized real-estate portal explicitly engineered for hyper-fast localized search indexing.', techStack: ['React', 'SSR', 'SEO Engine'], liveUrl: 'https://jessicabouzane.californiarealtyagents.com', imageUrl: '', type: 'client', order_index: 15, caseStudy: { overview: 'Local real estate depends on brutal algorithmic SEO. The entire site had to be Server-Side Rendered for maximum crawlability.', challenges: ['Dynamically generated property pages indexing poorly.', 'Slow map-pin clustering.'], solutions: ['Architected dynamic Next.js routes with aggressive getStaticPaths.', 'Implemented cluster-based WebGL map rendering.'], results: ['Dominated local hyper-specific search queries.', 'Flawless map interactions.'] } },
  { slug: 'accentadvisor', title: 'AccentAdvisor', category: 'SaaS', description: 'A complex educational SaaS portal bridging students with real-time video tutoring protocols.', techStack: ['WebRTC', 'React', 'Node.js'], liveUrl: 'https://accentadvisor.com', imageUrl: '', type: 'client', order_index: 16, caseStudy: { overview: 'Providing smooth VoIP/Video tutoring directly in the browser demands strict real-time protocol management.', challenges: ['WebRTC connection instability across disparate networks.', 'Synthesizing scheduling logic dynamically.'], solutions: ['Deployed global STUN/TURN resilient fallbacks.', 'Built a deeply custom calendar slot grid using React hook mechanics.'], results: ['Pristine, non-dropping video sessions.', 'Utterly frictionless tutor-to-student scheduling.'] } },
  { slug: 'allbirds', title: 'Allbirds', category: 'Sustainable E-Commerce', description: 'Engineered a highly performant, minimalist D2C storefront for a global sustainable footwear brand. Focused on sub-second paint times, fluid product exploration, and frictionless cart architecture.', techStack: ['React', 'Shopify Plus', 'WebGL', 'Tailwind'], liveUrl: 'https://www.allbirds.com', imageUrl: '', type: 'client', order_index: 17, caseStudy: { overview: 'Allbirds demanded an online experience as light and minimal as their physical products.', challenges: ['Heavy image payloads drastically slowing down First Contentful Paint (FCP) on mobile devices.', 'Complex variant switching causing DOM repaints and jank.', 'Integrating a heavy 3D rendering engine (WebGL) without locking the main thread.'], solutions: ['Implemented rigorous WebP/AVIF image pipelines with ultra-aggressive edge caching.', 'Architected a strict React state matrix to pre-fetch variant data.', 'Offloaded 3D WebGL rendering to a dedicated Web Worker.'], results: ['Achieved sub-second load times globally.', 'Zero-jank variant switching resulted in higher engagement per product page.', 'A stark, minimalist UI that perfectly mirrors the brand\'s sustainable ethos.'] } },
];

// ─── Seeder ───────────────────────────────────────────────────────────────────
export async function seedDefaultsIfEmpty(): Promise<void> {
  try {
    // --- Seed FAQs ---
    const { count: faqCount, error: faqCountErr } = await supabase
      .from('faqs').select('*', { count: 'exact', head: true });
    if (!faqCountErr && faqCount === 0) {
      const { error } = await supabase.from('faqs').insert(DEFAULT_FAQS);
      if (error) console.warn('FAQ seed failed:', error.message);
      else console.log('✓ FAQs seeded');
    }

    // --- Seed site_content ---
    const { count: scCount, error: scCountErr } = await supabase
      .from('site_content').select('*', { count: 'exact', head: true });
    if (!scCountErr && scCount === 0) {
      const { error } = await supabase.from('site_content').insert(DEFAULT_SITE_CONTENT);
      if (error) console.warn('site_content seed failed:', error.message);
      else console.log('✓ site_content seeded');
    }

    // --- Seed testimonials ---
    const { count: tCount, error: tCountErr } = await supabase
      .from('testimonials').select('*', { count: 'exact', head: true });
    if (!tCountErr && tCount === 0) {
      const { error } = await supabase.from('testimonials').insert(DEFAULT_TESTIMONIALS);
      if (error) console.warn('testimonials seed failed:', error.message);
      else console.log('✓ testimonials seeded');
    }

    // --- Seed blog posts ---
    const { count: bCount, error: bCountErr } = await supabase
      .from('blog_posts').select('*', { count: 'exact', head: true });
    if (!bCountErr && bCount === 0) {
      const { error } = await supabase.from('blog_posts').insert(DEFAULT_BLOG_POSTS);
      if (error) console.warn('blog_posts seed failed:', error.message);
      else console.log('✓ blog posts seeded');
    }

    // --- Seed projects ---
    const { count: pCount, error: pCountErr } = await supabase
      .from('projects').select('*', { count: 'exact', head: true });
    if (!pCountErr && pCount === 0) {
      // Insert in batches of 10 to avoid payload limits
      const batch1 = DEFAULT_PROJECTS.slice(0, 10);
      const batch2 = DEFAULT_PROJECTS.slice(10);
      const { error: e1 } = await supabase.from('projects').insert(batch1);
      const { error: e2 } = await supabase.from('projects').insert(batch2);
      if (e1 || e2) console.warn('projects seed failed:', e1?.message || e2?.message);
      else console.log(`✓ ${DEFAULT_PROJECTS.length} projects seeded`);
    }

  } catch (err) {
    console.warn('Seeding skipped (tables may not exist yet):', err);
  }
}
